//
//  LocalManagerConnections.swift
//  JoseRodriguez
//
//  Created by Jose Leoncio Quispe Rodriguez on 31/05/22.
//

import Foundation

class LocalManagerConnections : listVideoUseCase {
    func getListService(success: @escaping (Movie) -> Void, failure: @escaping (String) -> Void) {
        //Local database call
        /*
         
         ....................
         ....................
         ....................
         ....................
         ....................
         ....................
         ....................
         ....................
         ....................
         ....................
         
         
         */
    }
    
    
    
}
